#!/bin/bash

set -e -x

# Note: This uses my very own TG_TOKEN and TG_CHAT_ID in codespace/workspace secret

cd work/AnyKernel3

curl --upload-file *AnyKernel3*.zip https://transfer.sh/ > transfer.txt
TRANSFER_LINK=$(cat transfer.txt)

echo -e \
"
⚙️ Custom Kernel - Test Build by Crypton
✅ Build Completed Successfully!
🔃 Download Link (transfer): <a href=\"$TRANSFER_LINK\">Download Here!</a>
🚫 This Build is for Testing Purposes Only. Please test at your own risk.
" > tg.html

TG_TEXT=$(< tg.html)

curl -s -X POST "https://api.telegram.org/bot$TG_TOKEN/sendMessage" \
-d chat_id="$TG_CHAT_ID" \
-d parse_mode="HTML" \
-d text="$TG_TEXT"